### ISSUE TITLE
MongoDB validations 

### ISSUE THREAD

**Issue by yuvala15** [blue-stream/blue-stream-template#20]
Remove MongoDB validations from main feature -> validator folder if DB feature not chosen from generator.

**Comment by Ron537** [comment]
While working on this issue, please make sure there are no additional places to remove unused dependencies.

**Comment by yuvala15** [comment]
Got it!

**Comment by yuvala15** [comment]
Also correcting validations misspelling.

**Comment by AlmogVC** [comment]
Done
